### ISSUE TITLE
Record all steps in

### ISSUE THREAD

**Issue by TubsDK** [praxisdigital/assignsubmission_pxaiwriter#1]
Whenever a student press the do AI magic, the step must be recorded. 

The step should also be displayed in the pdf-fil and steps should be called called step 1.1, 1.2 etc. 

## TODO
- [x] Step 1 (1.0) should only contain the text that user has provided
- [x] Step 1.1 should contain text from AI response and user text from Step 1.0
- [x] Step 1.1 should have diff from the earlier step such as 1 - 1.1 or 1.1 - 1.2
- [x] Step 2 should diff from the last step of 1.x
- [x] ~~Improve diff handler (From hard code HTML to mustache template)~~
- [x] Step 2 or beyond should compare on the earlier step such as 2 diff 1 and 3 diff 2.
- [x] Exclude input text as diff in PDF annotation feedback.
- [x] Disable copy/paste in the for the text area.
- [x] The step 2 or higher should empty from the start, even after AI text got generated.
- [x] The step 2 or higher should copy the text from previous step if the step is empty.

**Comment by sampraxis** [comment]
# List of issues

## Critical issues
* Web service naming convention.
* Have a capability definition that is not belong to the plugin and hasn't been used in the system.
* Directly import jquery & mustache js libraries from the external source ([Link](https://github.com/praxisdigital/assignsubmission_pxaiwriter/blob/ebe11c7f73cb9ca8ba78ad7b317d8c831a3e4826/templates/assignsubmission_pxaiwriter_steps_student_form.mustache#L134-L135)).

## Technical issues
* Untestable code.
* Unused code & variables.
* Legacy web service implementation.
* Harcode all over the place. (HTML, web service call arguments, etc.)
* Web service doesn't validate correct context.
* Web service should limit to only user that can submit a submission.
* Not using Moodle built-in Javascript function such modal and error notification. (Directly use ``alert(error)``)
* The AMD module is outdated and still heavily rely on jQuery.

## Minor issues
* AMD module cannot be compile without using --force (AMD module doesn't compliant to the Moodle ESlint).

**Comment by sampraxis** [comment]
Test bundle:
#1 
#2
#3 

Branch: [smo_GH-dev_master](https://github.com/praxisdigital/assignsubmission_pxaiwriter/tree/smo_GH-dev_master)
Test by follow the description of the issues ( #1, #2, #3 )

**Comment by sampraxis** [comment]
Ready for testing.

Feature behaviors:
* Record steps
  * Plugin record the step that is current viewed.
    * It record when user press "Do AI magic", "Expand selection", "Next" and "Previous".
  * The steps that has been record should show up when you are grading a user submission with PDF annotation.
    * The steps will show as 1.1, 1.2, 2, 3
    * The fraction of the first step number will increase every times user change or generate new text in the first step.


Branch: [smo_GH-1_master](https://github.com/praxisdigital/assignsubmission_pxaiwriter/tree/smo_GH-1_master)

**WARNING!!!** You must test it from version **2023013100*  (branch: master). If you had test with **smo_GH-dev_master** or version: **2023041800** there is no upgrade script for that version.

#### Before you start make sure that you have version **2023013100** (**master** branch) installed.
Some of admin settings had been replace or no longer exists.
Such as **URL** and **Authorization**.

## Critical test
### Upgrade plugin from version 2023041800 to 2023050100 - Test upgrade script
1. Try to create an assignment and add AI writer submission to it. (This is for generate legacy data)
2. Upgrade the plugin from 2023041800 to 2023050100.
3. The **Authorization** is change to **OpenAI API token** just copy the setting from **Authorization** ``Bearer sk-...`` and set to **OpenAI API token** as ``sk-...``
4. Check the submission is still working.

### New installation
1. If you have assignsubmission_pxaiwriter already installed, then uninstall it.
2. Install the plugin with version 2023050100.
3. Create an assignment and add AI writer submission to it.
4. See if you have any issue with it.

**Comment by sampraxis** [comment]
Close these issues when you are done.
#2, #3, #6

**Comment by superfoght** [comment]
I can't get it to work

![Image](https://user-images.githubusercontent.com/2778015/236197178-57750f6b-1826-439f-890d-693c8fd56f1d.png)

**Comment by sampraxis** [comment]
@superfoght 

Ready to be test again.

**Comment by sampraxis** [comment]
Tested by Jesper.
There are some minor issues left such as
Disble copy/paste in the text box.
The input shouldn't count as diff when generate the AI text.

**Comment by sampraxis** [comment]
Ready for testing again.
Jesper had tested it last time. He might know what should be test from the previous test.

**Comment by sampraxis** [comment]
There is some unwanted behavior in grade overview, when choose "Word" in ``Granularity`` admin setting.

**Comment by sampraxis** [comment]
Ready for testing.
Last person had tested this was @superfoght

**Comment by superfoght** [comment]
There is a couple of scenarios we need to address.

Scenario 1.
1) Write a question to ChatGPT
2) Expand the selection of the result of the prompt. 
3) Now there is a step 1.3 where there is no changes recorded..

Scenario 2.
1) Write a question to ChatGPT
2) Add to the result from ChatGPT. Write something in the bottom
3) The changes are recorded in step 2, not as step 1.2

**Comment by sampraxis** [comment]
@superfoght 
Ready to be test again.

**Comment by superfoght** [comment]
After step 1. I tried expanding the output. Here is the result: 


![Image](https://github.com/praxisdigital/assignsubmission_pxaiwriter/assets/2778015/cadbf9e7-efea-4303-8d2c-1bd057f4e1d7)

It looks very weird..

I expanded it further in step 1.3 and it's also very weird. Basically unreadable:


![Image](https://github.com/praxisdigital/assignsubmission_pxaiwriter/assets/2778015/712a5e48-9b4d-494b-8d87-2d32ba6e406a)

**Comment by sampraxis** [comment]
@superfoght 
It's the diff library that render it that way.
We may need a better text diff library to make it more readable than the current library that the plugin is using...

Could you provide the link for the site that you were tested on? (Only if it wasn't on your local machine)
I will try to test with the same settings for this version and the stable version.

**Comment by superfoght** [comment]
It was on https://moodle40-morris.moodle.praxis.dk/my/

**Comment by sampraxis** [comment]
I tested with the stable version (master branch) and I got somewhat the same behavior from it.
As I mention in the previous comment, that we may need to use a different version of text diff library. And the current library we are using is ([d4h/finediff](https://github.com/D4H/php-finediff)).


![Image](https://github.com/praxisdigital/assignsubmission_pxaiwriter/assets/41996743/cc7f93e9-8439-45b8-a66c-ae95fd6c95ef)
![Image](https://github.com/praxisdigital/assignsubmission_pxaiwriter/assets/41996743/a8d20081-eaf9-4522-9a0e-13f04bd529bd)
![Image](https://github.com/praxisdigital/assignsubmission_pxaiwriter/assets/41996743/398e8e86-da14-44ab-a5b0-9810c21dec03)

**Comment by sampraxis** [comment]
Branch: **master**
Version: **2023060100**
