### ISSUE TITLE
AI writer improvement

### ISSUE THREAD

**Issue by sampraxis** [praxisdigital/assignsubmission_pxaiwriter#17]
## TODO
- [x] Add help text in the step guideline (Interaction with AI)
- [x] Bug attempts number become negative, when user remove a submission after user have already use all the attempts.
- [x] Add color indication for each step number.
- [x] Add background color to the step summary above the text area.
- [x] Refactor privacy API.

[AI writer improvement.pdf](https://github.com/praxisdigital/assignsubmission_pxaiwriter/files/12557067/AI.writer.improvement.pdf)

**Comment by sampraxis** [comment]
Related to #13

**Comment by sampraxis** [comment]
Ready for testing.
Please read this comment. https://github.com/praxisdigital/assignsubmission_pxaiwriter/issues/13#issuecomment-1727505188

**Comment by sampraxis** [comment]
@superfoght 
Ready for testing again.
