### ISSUE TITLE
Switch to gpt-3.5 api

### ISSUE THREAD

**Issue by TubsDK** [praxisdigital/assignsubmission_pxaiwriter#6]
We need to move to the gpt-3.5 model 

 https://platform.openai.com/docs/api-reference/chat/create 

This means added a few settings in site admin so that the user can choose to use gpt-3.5 

It also means that the syntax must be slightly altereret into the chat format: 
https://platform.openai.com/docs/guides/chat/chat-vs-completions

[
  {"role": "system", "content": "Du er en hjælpsom AI-asissisten, der skal hjælpe en studerende med at løse en opgave."},
  {"role": "user", "content": '{text}'}
]

List of model endpoint compatibility: https://platform.openai.com/docs/models/model-endpoint-compatibility

## IMPORTANT:
Chat completion API is still in beta.
This change is breaking ``mod_smartlink``.
This cannot test without refactor OpenAI API handler behavior in ``mod_smartlink``.

## TODO:
- [x] Change AI model admin setting from text to drop down list that plugin is supported.
- [x] Manage API request. ([Chat completion](https://platform.openai.com/docs/api-reference/chat/create) & [Text completion](https://platform.openai.com/docs/api-reference/completions/create) required different parameters)
- [x] Manage API response. ([Chat completion](https://platform.openai.com/docs/api-reference/chat/create) & [Text completion](https://platform.openai.com/docs/api-reference/completions/create) response different data)
- [x] Remove unused settings. API URL is no longer needed, since AI models have different URL such as ``text-davinci-002`` (text completion), ``text-davinci-003`` (text completion), ``gpt-3.5-turbo`` (chat completion)
- [x] Implement test.

**Comment by sampraxis** [comment]
This should be close together with #1 when it has passed the test.
